name: use my action
on: push

jobs:
  my_first_job:
     runs-on: ubuntu-latest
     steps: 
      - uses: actions/checkout@v2
        with:
          ref: action1
      - name: My first step
        uses: ./.github/actions/check-push-label