name: "Label Check"

on: push
jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    outputs:
      output1: ${{ steps.check_pr_labels.outputs.result }}
    steps:
      - name: Check PR labels action step
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ github.token }}
          labels: '["Ready For Review"]'

      - name: See result
        run: echo "${{ steps.check_pr_labels.outputs.result }}"

  check-labels:
      if: ${{ needs.check_pr_labels_job.outputs.output1 }}
      needs: check_pr_labels_job
      runs-on: ubuntu-latest
      outputs:
        output1: ${{ steps.automation.outputs.production }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run Automation
          id: automation
          run: echo "::set-output name=production::true"
  
  job2:
    runs-on: ubuntu-latest
    needs: check-labels
    steps:
      - run: echo ${{needs.check-labels.outputs.output1}}

  add-labels:
      runs-on: ubuntu-latest
      if: ${{ needs.check-labels.outputs.output1 }}
      needs: check-labels
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: add labels
          uses: actions-ecosystem/action-remove-labels@v1
          with:
            github_token: ${{ github.token }}
            labels: |
              Automation Failed

        - name: add labels
          uses: actions-ecosystem/action-add-labels@v1
          with:
            github_token: ${{ github.token }}
            labels: |
              Automation Passes
  
