# Run this workflow every time a pull request is created

name: "Ready For Review Checks"
on: 
  pull_request: 
    types: 
      - unlabeled
jobs:
  run-automation:
      if: ${{ github.event.label.name == 'Automation Failed' }}
      runs-on: ubuntu-latest
      outputs:
        output1: ${{ steps.automation.outputs.production }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Remove Useless labels
          uses: actions-ecosystem/action-remove-labels@v1
          with:
            github_token: ${{ github.token }}
            labels: |
              Automation Failed
              Automation Passes

        - name: Run Automation
          id: automation
          run: echo "::set-output name=production::false"

        - name: attach failure label
          if: steps.automation.outputs.production == 'false'
          uses: actions-ecosystem/action-add-labels@v1
          with:
            github_token: ${{ github.token }}
            labels: |
              Automation Failed
        
        - name: Check Result value
          if: steps.automation.outputs.production == 'false'
          id: finalResult
          run: exit 1

  build_process_3:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'Automation Failed' }}
    name: A Job That builds 3
    steps:
      - name: See result
        run: |
          echo "Hello build is running"
          sleep 10
  
  build_process_4:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'Automation Failed' }}
    name: A Job That builds 4
    steps:
      - name: See result
        run: |
          echo "Hello build is running"
          sleep 10
  
  success-labels:
      name: Final Results
      runs-on: ubuntu-latest
      needs: [run-automation, build_process_3, build_process_4]
      steps:
        - name: add labels
          uses: actions-ecosystem/action-add-labels@v1
          with:
            github_token: ${{ github.token }}
            labels: |
              Automation Passes 