# Run this workflow every time a pull request is created

name: "Add Automation Success Label"
on: 
  pull_request:
    types: [ labeled ]
jobs:
  add-labels:
      if: ${{ github.event.label.name != 'Automation Passes' }}
      runs-on: ubuntu-latest
      steps:
        - name: add labels
          uses: actions-ecosystem/action-add-labels@v1
          with:
            github_token: ${{ github.token }}
            labels: Automation Passes