# Run this workflow every time a pull request is created

name: "Update Automation Success Label"
on: 
  pull_request: 
    types: 
      - unlabeled
      - labeled
jobs:
  run-automation:
      if: ${{ github.event.label.name == 'Automation Failed' || github.event.label.name == 'Ready For Review' }}
      runs-on: ubuntu-latest
      outputs:
        output1: ${{ steps.automation.outputs.production }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run Automation
          id: automation
          run: echo "::set-output name=production::false"

  success-labels:
      runs-on: ubuntu-latest
      if: ${{ needs.run-automation.outputs.output1 == 'true' }}
      needs: run-automation
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: add labels
          uses: actions-ecosystem/action-add-labels@v1
          with:
            github_token: ${{ github.token }}
            labels: |
              Automation Passes
  
  fail-labels:
      runs-on: ubuntu-latest
      if: ${{ needs.run-automation.outputs.output1 == 'false' }}
      needs: run-automation
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: add labels
          uses: actions-ecosystem/action-add-labels@v1
          with:
            github_token: ${{ github.token }}
            labels: |
              Automation Failed