# Run this workflow every time a pull request is created

name: "Update Automation Success Label"
on: 
  pull_request: 
    types: 
      - unlabeled
      - labeled
jobs:
  run-automation:
      if: ${{ github.event.label.name == 'Automation Failed' || github.event.label.name == 'Ready For Review' }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: ./.github/workflows/github-action-sample
        - run: echo "Action called goooooood!!"