# Run this workflow every time a pull request is created

name: "Update Automation Success Label"
on: 
  pull_request: 
    types: 
      - unlabeled
      - labeled
jobs:
  run-automation:
      if: ${{ github.event.label.name == 'Automation Failed' || github.event.label.name == 'Ready For Review' }}
      runs-on: ubuntu-latest
      outputs:
        output1: ${{ steps.automation.outputs.production }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run Automation 1
          uses: Manushivam-HMP/Github-Actions/.github/workflows/github-action-sample

        - name: Run Automation 2
          uses: Manushivam-HMP/Github-Actions/.github/workflows/check-push-label
